spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dream?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
    username: root
    password: mytest
  thymeleaf:
    cache: false

